#!/bin/csh

set first_name = ""
set last_name = ""
set id = ""

while (1)
    echo -n "  vBalance [Input] : Add First Name : "
    set first_name = $<
    
    set test = `echo $first_name | grep "^[A-Za-z]\+$"`
    if ($test == "") then
        echo "  vBalance [Error] first_name: Employee name should only contain letters and no spaces!"
        continue
    endif
    break
end
while (1)
    echo -n "  vBalance [Input] : Add Last Name : "
    set last_name = $<
    
    set test = `echo $first_name | grep "^[A-Za-z]\+$"`
    if ($test == "") then
        echo "  vBalance [Error] first_name: Employee name should only contain letters and no spaces!"
        continue
    endif
    break
end

while (1)
    echo -n "  vBalance [Input] : Add ID : "
    set id = $<

    set test = `echo $id | grep "^[0-9]\{5\}$"`
    if ($test == "") then
        echo "  vBalance [Error] id: Company ID must be exactly 5 consecutive digits!"
        continue
    endif
    set test = `grep "$id" employees`
    if ("$test" != "") then
        echo "  vBalance [Error] id: Company ID already exists!"
        echo "  $test"
        continue
    endif

    break
end

printf "%-10s %-10s \t%-10s \t%-5s \t%-5s \t%-5s \t%-15s \t%-5s\n" "$first_name" "$last_name" "$id" "21" "11" "10" "Thu Sep 21 00:00:00 EEST 2022" "0">> employees
echo "  vBalance [Info] add record: Record Added"
